server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/logistics
    username: root
    password: 123456

  devtools:
    remote:
      restart:
        enabled: true
    restart:
      additional-paths: Pinda/src/main/java
      exclude: static/**

mybatis:
  mapper-locations: classpath:org/example/dao/*.xml
  type-aliases-package: org.example.pojo


thymeleaf:
  model: HTML5
  encoding: UTF-8
  prefix: classpath:/templates/
  suffix: .html
  content-type: text/html
  cache: false